apiVersion: apps/v1
kind: Deployment
metadata:
  name: automotive-app
  labels:
    app: automotive-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automotive-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: automotive-app
    spec:
      containers:
        - name: automotive-app
          image: 'anshmundra/automotive-app:latest'
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
